### ISSUE TITLE
Jenkins Credential ID

### ISSUE THREAD

**Issue by pavdigital** [mlabouardy/pipeline-as-code-with-jenkins#33]
What is the jenkins_credentials_id in 
```
data "template_file" "user_data_jenkins_worker" {
  template = "${file("scripts/join-cluster.tpl")}"
 
  vars = {
    jenkins_url             = "http://${aws_instance.jenkins_master.private_ip}:8080"
    jenkins_username       = var.jenkins_username
    jenkins_password        = var.jenkins_password
    jenkins_credentials_id = var.jenkins_credentials_id
  }
}
```

I have tried making it reference an actual pem key on disk which I use to ssh onto the instances but I can't seem to manage to get the workers to join master

```
data "template_file" "user_data_jenkins_worker" {
  template = file("scripts/join-cluster.tpl")

  vars = {
    jenkins_url             = "http://${aws_instance.jenkins_master.private_ip}:8080"
    jenkins_username        = var.jenkins_username
    jenkins_password        = var.jenkins_password
    jenkins_credentials_id = file("${path.module}/jenkins-key-pair.pem")
  }
}
```

**Comment by Sijibomii** [comment]
Hey, I currently have this same issue. Please how did you get the jenkins_credentials_id

**Comment by pavdigital** [comment]
In the end I gave up and used Jenkins swarm plugin instead to connect nodes to master. So much easier.

**Comment by Sijibomii** [comment]
Alright Thank you!

**Comment by Monarene** [comment]
How did you used jenkins swarm plugin to connect nodes to mast @pavdigital

**Comment by mlabouardy** [comment]
The jenkins credentials ID is the ID of the credentials where the SSH key pair is stored: https://github.com/mlabouardy/pipeline-as-code-with-jenkins/blob/master/chapter4/distributed/master/scripts/node-agent.groovy#L16
