### ISSUE TITLE
running  packer build template.json shows error

### ISSUE THREAD

**Issue by thulsidk1** [mlabouardy/pipeline-as-code-with-jenkins#48]
Greetings. Thanks for your book "pipeline-as-code". I'm having issue in running the packer in ec2

ubuntu@ip-172-31-43-214:~/pipeline-as-code-with-jenkins/chapter4$ ls
distributed  packer  standalone
ubuntu@ip-172-31-43-214:~/pipeline-as-code-with-jenkins/chapter4$ cd standalone/
ubuntu@ip-172-31-43-214:~/pipeline-as-code-with-jenkins/chapter4/standalone$ ls
setup.sh  template-multiple-builders.json  template-with-filter.json  template.json
ubuntu@ip-172-31-43-214:~/pipeline-as-code-with-jenkins/chapter4/standalone$ packer build template.json
amazon-ebs output will be in this color.

Build 'amazon-ebs' errored: error validating regions: InvalidEndpointURL: invalid endpoint uri
caused by: parse https://ec2.aws/ [REGION.amazonaws.com/](http://region.amazonaws.com/): invalid character " " in host name

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: error validating regions: InvalidEndpointURL: invalid endpoint uri
caused by: parse https://ec2.aws/ [REGION.amazonaws.com/](http://region.amazonaws.com/): invalid character " " in host name

==> Builds finished but no artifacts were created.
ubuntu@ip-172-31-43-214:~/pipeline-as-code-with-jenkins/chapter4/standalone$ export AWS_ACCESS_KEY_ID=""
ubuntu@ip-172-31-43-214:~/pipeline-as-code-with-jenkins/chapter4/standalone$ export AWS_SECRET_ACCESS_KEY=""
ubuntu@ip-172-31-43-214:~/pipeline-as-code-with-jenkins/chapter4/standalone$ export AWS_DEFAULT_REGION=""
ubuntu@ip-172-31-43-214:~/pipeline-as-code-with-jenkins/chapter4/standalone$ packer build template.json
amazon-ebs output will be in this color.

Build 'amazon-ebs' errored: error validating regions: InvalidEndpointURL: invalid endpoint uri
caused by: parse https://ec2.aws/ [REGION.amazonaws.com/](http://region.amazonaws.com/): invalid character " " in host name

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: error validating regions: InvalidEndpointURL: invalid endpoint uri
caused by: parse https://ec2.aws/ [REGION.amazonaws.com/](http://region.amazonaws.com/): invalid character " " in host name

==> Builds finished but no artifacts were created.
Any help would be appreciated.

**Comment by mlabouardy** [comment]
Hey @thulsidk1 
It would help if you filled the `variables` section in [template.json ](https://github.com/mlabouardy/pipeline-as-code-with-jenkins/blob/master/chapter4/standalone/template.json#L3) by providing the following:

- the name of the AWS region where you want to create the AMI
- the name of the AWS profile to use to deploy the AMI
- the source AMI 2 ID
- set the instance type to `t2.medium` by default
